CREATE TABLE [dbo].content
(
    [ID] INT NOT NULL IDENTITY(1, 1),
    [WRITERNAME] NVARCHAR(100) NULL,
    [TITLE] NVARCHAR (100) NULL,
    [TIMEOFSUBMITION] NVARCHAR (100) NULL,
    [TIMEOFREADING] NVARCHAR(100) NULL,
    [IMG] NVARCHAR(100) NULL,
    [BODY] NVARCHAR(1000) NULL,
    [CATEGORY] NVARCHAR(100) NULL,
    PRIMARY KEY (ID)
);